### ISSUE TITLE
Not working with activestorage 6.0.1 ?

### ISSUE THREAD

**Issue by srgoldman** [ashishprajapati/activestorage-dropbox#6]
I've configured the dropbox entry in my storage.yml file:
```
dropbox:
  serivce: Dropbox
  access_token: <%= ENV['EMBROIDERY_DROPBOX_TOKEN'] %>
```
but I'm getting the following error when trying to do the direct upload (works with other active storage providers):
```
NoMethodError (undefined method `url_for_direct_upload' for nil:NilClass):
  
activestorage (6.0.1) app/models/active_storage/blob.rb:160:in `service_url_for_direct_upload'
activestorage (6.0.1) app/controllers/active_storage/direct_uploads_controller.rb:19:in `direct_upload_json'
activestorage (6.0.1) app/controllers/active_storage/direct_uploads_controller.rb:9:in `create'
actionpack (6.0.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.1) lib/abstract_controller/base.rb:196:in `process_action'
```

And yes, the env var is set with the correct token (afaik).

**Comment by srgoldman** [comment]
I'm an idiot - typo in the storage.yml file. However, it still doesn't work because `url_for_direct_upload` is still undefined. I have an alternative way to get it working but it'd be nice to work for direct uploads.

**Comment by ashishprajapati** [comment]
Ref https://github.com/ashishprajapati/activestorage-dropbox/issues/16
